name: Bump Tag

on:
  pull_request:
    types: ["closed"]
    branches: ["main"]

jobs:
  bump-tag:
    if: github.event.pull_request.merged == true
    uses: openclimatefix/.github/.github/workflows/bump_tag.yml@main
    secrets: inherit
