name: CI

on: 
  push:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  checks:
    name: Run tests for Python ${{ matrix.python-version }} on ${{ matrix.runs-on }}
    runs-on: ${{ matrix.runs-on }}
    needs: [pre-commit]
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.12"]  # test oldest and latest supported versions
        runs-on: [ubuntu-latest]  # can be extended to other OSes, e.g. [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          allow-prereleases: true

      - name: Install package
        run: python -m pip install .[dev]

      - name: Test package
        run: >-
          python -m pytest
